# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17aaef06a207d5a98b766dc9e2ae3863717b1fb4c32afb3ce6ccd10efdccc5ea4db9fa168c7857920ff6a1536a37420853dd7e3710d477433fb2a3eaf08398c1

test:
  secret_key_base: 9ea898a71ef4ed545f636f0f321b3fceb302a7292bacb55a8b3a6a23111c8a9930ddac12a25c348ccbc22c2de216ba377bfdd4b504f89c4b1e72c36efa9b5af4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
